### PR TITLE
[LIB-665] removed duplicated private register method

### PR DESCRIPTION
**Pull request by jaskooo**

### CODE REVIEW

**Comment by lifcio** [comment]
Looks good. You also need to add `nullable` to user profile in the declaration.

**Comment by jaskooo** [comment]
There's no declaration in header for this method. It is private method for internal use only

**Comment by lifcio** [comment]
I meant 
```objc
+ (void)registerWithUsername:(NSString *)username password:(NSString *)password userProfile:(SCUserProfile *)userProfile completion:(nullable SCCompletionBlock)completion;
```
and 
```objc
+ (void)registerWithUsername:(NSString *)username password:(NSString *)password userProfile:(SCUserProfile *)userProfile inSyncano:(Syncano *)syncano completion:(nullable SCCompletionBlock)completion;
```

**Comment by jaskooo** [comment]
ok, but in those methods that you pointed `userProfile` is not nullable. It should be provided

**Comment by lifcio** [comment]
Ahh, ok, right. I missed that! LGTM then.

**Pull request merged**
