### PR TITLE
Create new user without logging him in automatically

### PR DESCRIPTION
**Pull request by lifcio**
Added a new static method in SCUser to allow registering users without login him automatically. It also returns the newly created user so you can, for exemple, update its profile right away. Useful in cases where an admin of a private system wants to register users, because they can't use the app without being invited.

by @patricktremblay1

### CODE REVIEW

**Comment by lifcio** [comment]
@patricktremblay1 I made small changes - name of the blog, and I hid method using `API Client`, to add one using `Syncano` object instead. Let me know if it looks good.

@jaskooo @trapi I need to add test, so you can wait with review.

**Comment by patricktremblay1** [comment]
@lifcio Looks good, thanks.

**Comment by jaskooo** [comment]
I think this method shoulde be named `addNewUserWithUserName:paasword:completionBlock:`

**Comment by lifcio** [comment]
Ok, thanks, I think it makes sense - so we can keep method `register` to auto-login user, and `add` to just add him, without login. 
I will write tests this week and try to merge it before Sunday.

**Comment by lifcio** [comment]
I'll close it for now until tests are done and reopen when they are committed to this branch.

**Comment by lifcio** [comment]
@patricktremblay1 It should be on cocoapods on Monday

**Pull request merged**
